steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['DOCKER_BUILDKIT=1', 'build', '-f', 'dockerfiles/train_model_torch.dockerfile', '-t', 'gcr.io/$PROJECT_ID/train_image:lates', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/train_image:latest']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args:
#   - 'run'
#   - 'deploy'
#   - '<service-name>'
#   - '--image'
#   - 'gcr.io/$PROJECT_ID/<container-name>:latest'
#   - '--region'
#   - '<region>'
