version: "3"
services:
  trainer:
    image: trainer:latest
    build:
      context: .
      dockerfile: dockerfiles/train_model.dockerfile

    env_file:
      - personal/secrets.env

  predict:
    image: predict:latest
    build:
      context: .
      dockerfile: dockerfiles/predict_model.dockerfile
