hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
hyperparameters:
  batch_size: 64
  data_fraction: 1.0
  learning_rate: 1e-4
  max_epochs: 50
  num_workers: 23
wandb:
  entity: dtu_mlops_project
  name: run_${now:%Y-%m-%d_%H-%M-%S}
  project: dtu_mlops_wandb_deploy
